try{
    throw Error('fff');
  }catch(e){
    console.log(e);
  }